const getters = {
    sidebar: state => state.app.sidebar,
    language: state => state.app.language,
    device: state => state.app.device,
    loginType: state => state.app.loginType,
    uploadImageUrl: state => state.app.uploadImageUrl,
    defaultImage: state => state.app.defaultImage,
    schoolId: state => state.app.schoolId,
    industry: state => state.app.industry,
    job: state => state.app.job,
    subject: state => state.app.subject,
    rootCourseCategoryId: state => state.app.rootCourseCategoryId,
    visitedViews: state => state.tagsView.visitedViews,
    cachedViews: state => state.tagsView.cachedViews,
    token: state => state.user.token,
    name: state => state.user.name,
    adminType: state => state.user.adminType,
    loginName: state => state.user.loginName,
    userId: state => state.user.userId,
    userCode: state => state.user.userCode,
    corpCode: state => state.user.corpCode,
    hasBgk: state => state.user.hasBgk,
    ucPrefix: state => state.user.ucPrefix,
    permissions: state => state.user.permissions,
    // eslint-disable-next-line camelcase
    permission_routers: state => state.permission.routers,
    addRouters: state => state.permission.addRouters,
    nowRouters: state => state.permission.nowRouters,
    errorLogs: state => state.errorLog.logs,
    ajaxIng: state => state.ajax.ajaxIng,
    temporaryId: state => state.temporary.temporaryId,
    selectedIds: state => state.project.selectedIds,
    cacheViews: state => state.cache.cachedViews
};
export default getters;
