module.exports = {
    NODE_ENV: 'production',
    ENV_CONFIG: 'prod',
    ENV_CODE: 'prod',
    BASE_API: '/api',
    UC_API: '/api/veln-uc',
    STU_API: '/api/veln-stu',
    KM_API: '/api/veln-km',
    FACE_API: '/api/veln-face',
    AUTH_API: '/api/veln-auth',
    WORK_API: '/api/veln-work',
    CERT_API: '/api/veln-cert',
    SURVEY_API: '/api/veln-qtn',
    SCORE_API: '/api/veln-is',
    CONVERT_API: '/api/veln-convert',
    PE_SCREEN_API: '/api/veln-pe/pe',
    PE_API: '/api/veln-pe/pe',
    MP_API: '/api/veln-mp',
    FS_API: '/api/qgyun-service-fs-manager',
    CS_API: '/api/veln-cs',
    SCH_API: '/api/veln-sch',
    NEWS_API: '/api/veln-news',
    MALL_API: '/api/veln-mall',
    CDN_URL: 'https://zjj.e-nai.cn/qgyun-static',
    SHARE_PREFIX: 'https://kty.kttx.cn',
    STATIC_API: '',
    CUSTOMER_LINK: ''
};
